#pragma once
#include <vulkan.h>
#include <iostream>
#include <stdexcept>
#include <cstdlib>
#include <vector>
#include <map>
#include "include/GLFW/glfw3.h"
#include "include/glm/vec4.hpp"
#include "include/glm/mat4x4.hpp"
#define GLFW_INCLUDE_VULKAN
#include <numeric>
#include <set>
#include "Validator.h"
#include "Utils.h"
#include "EngineCommon.h"
//#include "include/spdlog/spdlog.h"
#include <algorithm>
#include "ShaderLoader.cpp"
